services:
  db:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
  aws:
    image: localstack/localstack:s3-latest
    ports:
      - 4566:4566 # LocalStack Gateway
    volumes:
      - localstack-volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  localstack-volume: